spring.application.name=backend

external.movie-api.base-url=https://phimapi.com

spring.datasource.url=jdbc:postgresql://localhost:5432/netflex
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#
#logging.level.org.springframework.web=DEBUG
#logging.level.feign=DEBUG
spring.jackson.default-property-inclusion=NON_NULL
spring.jackson.deserialization.fail-on-unknown-properties=false

paypal.client.id=ARMC82prBKZcz22p5XU8jsr5Fzfxc8YDyeUNv_yUajVQ_GSoDhtmOtrYmWRg_urmH0Tx1Y4RxJOEaZWl
paypal.client.secret=ED_iNYoO3NaQP6jQ0CxDW_nrP9OWjnlDZHngjReZnU2Px_z9YDdpVjW31pIgxYrDQUk1DSD_wDcEBz58
paypal.base.url=https://api-m.sandbox.paypal.com

app.jwt.secret=uo490OWB0JeDGJkx9vYnUXVq1uo+oy9euMV1NVgrt2YnPr4QRXcB7vRGG6uN3VMT
app.jwt.expiration=86400000
app.jwt.refresh-token-expiration=604800000

springdoc.swagger-ui.path=/api/v1/document/swagger-ui.html
springdoc.api-docs.path=/api/v1/document/api-docs
